#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define SERVER_QUEUE_NAME "/CS2017_SERVER_QNAME"
#define CLIENT_QUEUE_NAME "/CS2017_CLIENT_QNAME"
#define SERVER_MSG_SIZE   10000

#define NB_THREADS 8

#endif // CONFIG_H_INCLUDED
